### PR TITLE
Create Java program to solve N Queen Problem using

### PR DESCRIPTION
**Pull request by SAURABHTIWARIVBSPU**

### CODE REVIEW

**Comment by SAURABHTIWARIVBSPU** [comment]
Please assign for this program

**Comment by frigid-lynx** [comment]
Please add it in my cpp DSA repo i will surely merge it add using cpp and
add something that is unique and complex algo

**Comment by SAURABHTIWARIVBSPU** [comment]
Bro give me our contact number

**Comment by frigid-lynx** [comment]
M a girl bro ...

**Comment by frigid-lynx** [comment]
Please tell how you created the insights on your profile

**Comment by frigid-lynx** [comment]
Please star this repo for support

**Pull request merged**
